spring:
  profiles:
    active: application

    # Oracle settings
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: samane
    password: 46487379
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    show-sql: true
    properties:
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.hazelcast.instance_name: TTCU
    hibernate:
      ddl-auto: none

security:
  jwt-public-key: MIIJKQIBAAKCAgEAtcEq273/3WqDqwEgdWzHC6RBNQqOxrdireAjnPLiJ6NeTYUmdmSbF6CMXDTsW4bOzyGfu6PMkn0MOSs/7nyoXk6EJxkRoXtfKuL9W159V2IzZ0hCIPUehVVbRf5JU0BeU7sjomvsSasjZSir1vS2f8xCv7+S8njJ55WDwPs/Yf4jMcwaAgWMZusepPJQPpK+tOoIunS8kLGJJbftAL+qsdcWjGArGFVLMIrf8Ic0dcOVKdalFjOkDAbvpTvzlWKDk6M80R7EzWCljW+2SqSKm3kZwnNDgNaAt49UKa2Oqr0Q3P4nIdMcYG6ylZjWTEo0W//717HWqWM1Uub9Wc4kUpxB7Cq2J5lfdOXXko08L+ueBrgme7jMhiszTg+8mPPWBYhDbyo92q8qKY6XLrsmTDLqyRS9ydsHQQjL1iuisvpU1KDJF9n1zLAMcLArQ7wQCGr7xl+/p85aA3gWYOXWdvdjrr/VVzLSDbHMteff6HiRxkd4  yJQ6c81v31qCdKKOaxm4CpTTBpQ0OxCVXg55fplZady7ByeTvhkiE2BPxn9ta1eaKgys1g4bPczTfXxx25DYWFIMAXUYqsZZuNuo53/rBuAepkBhqMMxmZqjCGnPE1LIq1kQKWp3u7HQxwMoyA1AP7zW/wsu6YnyaE57Q7bVHTISy+TukAraF0pD50sCAwEAAQKCAgEAjgB8vrBEbrZgZsN7m6LAJK1RMOKtyD3RAC4lRONSpEt0SzajZU6XCa+q2gOTQrMhcx0/EjgYhb7jROswiOCmHwBTKcThTHv6T6SG89LwNMyJgsEmwV8hWGTm6dmRalTZHawRXD3bn3bxMYDEOS56Q4DQCcXgRkbu4FulU6o4zBPlZWukSj4RgvthtteGsEywaOKMrTi1doruryRzK+mTsFxuxoAAS4OgOi3WZrML3pJPQR/tXVo9ahQlOcCMQAN272tTAcN7WUaQMd+82baSgIPuB0lMzSVJ7aAyzllGJMmQmkiLRFcPTZxPNKfzjilPnS1zkwLjxvW23K2R9Y8kOoHARnYTKtM+v1pxJn/LHgF5r1iFEGEa14x4DSgXakytp7bRoK0ATRccLIP9EundVZidts9G2SV8WYkQkbyUehk3nyX6YhVcHj1CWG4nU2zIjSbtPypJz87E3vBwaHaZgXXjVljFyG4r1LHZQ8yWkOX/lna419YLNNO7ihoGLqA0kuuhkgMQEP7BjYzjeqYSkfGDNsjfuPJBptd9KoEnyH4zk250Ez5o+H63HiFlglX6WB+NRRuiK+1QfCmoP8xwxoPzO0xQIWpkVJmDEadrzwmqjcCJfQSPXEADbqjOiSyUiZCCzm9tCKigeEWXInUTp15UXdnpfIMbZMBhUSBUawkCggEBANjBARhbyu5toKeoM7MMD24g9q2NGsqs+BHJCosHUuY0d3KKUDjA8OLfqbc7hqxGq2GauxiuOVycXP5VuBbdlawMoDCe2hdnLHJ1PXgJMvmHzvccLnYMyPqyNpxLPraynYUzydRvDX14fhwJzuq+o48NMKytUmG/k3sLgJnLdMqD95AzBY0GtT025AWgIAyK2kAV0JAkxCMubm7P/Ij6aCUDwBP0nN5HBa0AIC3obaX/9GI70HgHYXeukKOIeaZN6/jrBqBtXphSVGhgguUEgB+tihHaxhJh98gcQLBQo51fXv4oUawp+G47SBwqpgVaBCB8XbpRmftgbGFxdw19zF8CggEBANap3qppMlVKs2yDynYV9Z6nM3pyDnL7/7dQFk9xgCtcDBCqreME1wCG0VXte8GJblIiNIcDrZIIrnJqLyeF1vyHOrRsYId8DdUQVutwU/ck59M0sWYSUHjjLFdnjgrzyrrdJJSLQ8YjNvjH3mev1+kmhxBgWF6XmagCnd8L8PAWoo2sAlerBPcVHflUMGAmjHMd47lwI9Gw04bh+IgERSPFR8zH90rnq/42seJvoWRHOZzeNqlwhA3Z99jo3kVJXmhtlVPMlvRIHHlL74jHkptJzTv0D/5MPE6E0x/fbsroQ0p6Z4lvu+d3d+albPrHZsPcPotAeGuT/Vrpt0C4jJUCggEBAM5wM+zRMBuZidNkXaj/qYqIFqkApS23Q6Ucxs/XL9tUyRbsKK+FA2fxAaEkLoXR4NRbHCrLdJKB0gfh+Cy+6hgtBjyIbsqvVyPECcFTcZs6/6FW0+FXF+u85EpDV/2FbIU659VN15lSszldFhd5bimGtH8hrD6wyXP9ZoQTxK5Etfo+veCtLNyadN3uvdd0P52dqUA/5BZl2IPtz2VeqOXoBn57ERSarAsy/XL71cKuXkFZGpnW3buxJMy75LDBsicnIO6We+uzLfUjRkd829JP5BpRNSi46ddLIUlL5Ci0drK2D+NbLeM+ztUUwX6DVz7hdBtKMM+77D16ZZsR3x0CggEAUm/J4wejHL4jSXkTN2YXfWYYjt1eTyoXef53kuqznfMrbvsc7CHfr4QWwDkDXb+5bjFUmsT+0yYiWC4PDc6IUVJdaQx1xZIOfdRYjPIGTNMPdDy4I8rEvKgBT0+lbO9S25AxjBovXNgJNGENOCR/djolhFR7m1f82lim6BFd5dXLdzynaaNztK+XYzjBmysypMLFwWEfYFfX4+TD3PhG1QXeHPZuMYXmtymqBpt4D1qK9YMg2tEq5Wbfl51WPqV+a/wpbJUVI5rN1Ick5hI+awRcnLmNqsr8HetEaOkVUzb/IIsBV/Zg4vMuSJUe1O/etzjNjAymMioTEebPSTuWQQKCAQB7JTCPgKy3C/Uf7/UDOzR1A15HfKsc0oykmsismZVLTKjLYY0M8H6QfQu0p1nCbOl4N0H6MTKQXkNaDCOp9V4qMVn4dzuSrDTDy/Ls6Kb3hMIvnQ+vF/kPjyfztAZ2BsCUNql8g4Rs5OUqMIjOXahYn39+n6tcJ5DEs0K02Pufs7T0ixjHkK1AXTZJkWl/KOkVSZMvyw8tvjftkNxxREq50CSiTNnqNFVog9wYChpH0nVk0rQ3wT3u81OMnor/8YttWnCuqJav+vCWFJT1baskD0SnbNYNCDOkM3NlXaL9M91DMlFxJuMJUJRKdU+uSfMxA18LjsWlKle/1drKHZtq



server:
  port: 8082







