spring:
  profiles:
    active: application

    # Oracle settings
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: samane
    password: 46487379
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    show-sql: true
    properties:
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.hazelcast.instance_name: TTCU
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          se


server:
  port: 8082







